**01-03 Pandas and Numpy**

In [1]:
import pandas as pd
import numpy as np
# 1차원 배열
vec = np.array([1, 2, 3, 4, 5])
print(vec)
# 2차원 배열
mat = np.array([[10, 20, 30], [ 60, 70, 80]])
print(mat)
print('vec의 타입 :',type(vec))
print('mat의 타입 :',type(mat))

[1 2 3 4 5]
[[10 20 30]
 [60 70 80]]
vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>


In [3]:
from sklearn.model_selection import train_test_split
# 임의로 X와 y 데이터를 생성
X, y = np.arange(10).reshape((5, 2)), range(5)

print('X 전체 데이터 :')
print(X)
print('y 전체 데이터 :')
print(list(y))


X 전체 데이터 :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 전체 데이터 :
[0, 1, 2, 3, 4]
