**02-02 텐서 조작하기**

In [1]:
import numpy as np

t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)
type(t)

[0. 1. 2. 3. 4. 5. 6.]


numpy.ndarray

In [2]:
print('Rank o t:', t.ndim)
print('Shape of t:', t.shape)

Rank o t: 1
Shape of t: (7,)


In [3]:
import torch

t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


**02-03 텐서 조작하기(2)**

In [6]:
#뷰(view)

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [8]:
print(ft.shape)

torch.Size([2, 2, 3])


In [9]:
#차원 바꾸기 - 3차원을 2차원으로
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [10]:
#차원 바꾸기 - 3차원 텐서의 크기 바꾸기
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)


tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [11]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [14]:
ft.squeeze()

tensor([0., 1., 2.])

In [21]:
#연결하기
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

a=torch.cat([x,y],dim=1)
b=a.view([-1,2,2])
print(b)
print(b.shape)
print(a.shape)

tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])
torch.Size([2, 2, 2])
torch.Size([2, 4])


**02-04 파이썬 클래스**

In [23]:
class Calculator:
    def __init__(self):
        self.result = 0

    def add(self, num):
        self.result += num
        return self.result

cal1 = Calculator()
cal2 = Calculator()

cal1.add(1)
print(cal1.add(2))

3
